# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'cloudyridge1 (702f1b82-c5a3-4907-9154-3422eaf5f48e)'
    subscriptionId: '702f1b82-c5a3-4907-9154-3422eaf5f48e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'nodehw-rg'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
